### ISSUE TITLE
do not work in retina device on cocos2dx 3.2

### ISSUE THREAD

**Issue by manjureddy48** [raymondlu/super-animation-samples#35]
anybody help please, the "super animation node " does not work in retina device properly on cocos2dx 3.2

**Comment by raymondlu** [comment]
can you give me more information? thank you.

**Comment by manjureddy48** [comment]
Hi,

In iPad normal it is working fine, but when it comes to iPad retina
animations are coming with large sizes and position also varies in ipad
retina devices.
Sorry for my english.
I am waiting for your reply.

**Comment by raymondlu** [comment]
i don't have an iPad retina device, but I run my sample in simulator, and it works properly.

**Comment by raymondlu** [comment]
FYI, there is an unknown bug for 64bit, so don't compile your game as 64bit version.

**Comment by raymondlu** [comment]
hey, guys, I have just fixed the 64bit bug for cocos2d-x-3.1 and cocos2d-x-3.2, please have update your code, any problem please let me know.

**Comment by manjureddy48** [comment]
Still this issue is not solved for cocos2d-x -3.2 version,so please review once and update the code to work in retina devices also.You can also find difference in following screenshots in normal and retina ipad.
![normalipad](https://cloud.githubusercontent.com/assets/8862562/4544717/8c14fae6-4e35-11e4-84f7-adcbb4b862b1.png)
![retinaipad](https://cloud.githubusercontent.com/assets/8862562/4544723/94bc1cd8-4e35-11e4-8d13-4aa60935cdfc.png)

**Comment by krithikb007** [comment]
Any update on this issue ?

**Comment by raymondlu** [comment]
@krithikb007 can you email me with  a sample to reproduce this bug?

**Comment by krithikb007** [comment]
Sure here it is.
https://www.dropbox.com/s/zehh2sgtxp35qs1/SuperAnimationRetinaDeviceBug.zip?dl=0

**Comment by raymondlu** [comment]
@krithikb007 sorry, I cannot download your zip file since dropbox is blocked by the government.
:-(

**Comment by krithikb007** [comment]
Can you suggest some alternatives  for file share ?

**Comment by raymondlu** [comment]
@krithikb007 maybe you can create a public repo in github, then send me the git address.

**Comment by krithikb007** [comment]
Can you provide your mail id ? So i can mail the class files ?

**Comment by raymondlu** [comment]
@krithikb007 you can find my email in the source code...

**Comment by kenjisaito** [comment]
Hi,

In my case, it resolved by enabling scale transform code which are commented out in SuperAnimNode::onDraw.

I changed code like below.
SuperAnimNodeV2.cpp:

```
void SuperAnimNode::onDraw(const Mat4 &transform, bool transformUpdated)
{
    ...
    //float aPixelToPointScale = 1.0f / CC_CONTENT_SCALE_FACTOR();  // DELETE
   float aPixelToPointScale = 1.0f / CC_CONTENT_SCALE_FACTOR();  // ADD
    ....
    // convert to point
    //sAnimObjDrawnInfo.mTransform.Scale(aPixelToPointScale, aPixelToPointScale);  // DELETE
    sAnimObjDrawnInfo.mTransform.Scale(aPixelToPointScale, aPixelToPointScale);  // ADD
    ...
    if (mIsFlipX) {
        float aWidthinPixel = getContentSize().width * CC_CONTENT_SCALE_FACTOR();  // DELETE
        float aWidthinPixel = getContentSize().width;  // ADD
    ...
    if (mIsFlipY) {
        float aHeightinPixel = getContentSize().height * CC_CONTENT_SCALE_FACTOR();  // DELETE
        float aHeightinPixel = getContentSize().height;  // ADD
```

raymondlu, why the code ware commented out?
Does it cause some other problems, if enables scale transform?
